### ISSUE TITLE
Region errors with window forms.

### ISSUE THREAD

**Issue by Blackfire363** [BenFradet/RiotSharp#126]
I would like to use RiotSharp to develop desktop applications with the riot api, however when i call something like: var summoner = api.GetSummoner(Region.euw, "StopOFlop"); 
I get the error: 'System.Drawing.Region' does not contain a definition for 'euw'

Is there a way to change Region.euw to where it would not conflict with the system drawing so I can use it, instead of using a console application?

**Comment by Ijwu** [comment]
It's likely a good idea to simply alter your using statement or use the fully qualified name of the type you're trying to get at.

What I mean is that you can specify "which `Region`" you're talking about by altering your using statement. This might help:
```c#
using Region = RiotSharp.Region;
```

Alternatively, whenever you use the `Region` `enum` you may use the fully qualified name:
```c#
var summoner = api.GetSummoner(RiotSharp.Region.euw, "StopOFlop"); 
```

If you are _not actively_ using the `System.Drawing.Region` type then I suggest going with my first suggestion. Otherwise it may be wise to go with the second.

**Comment by Blackfire363** [comment]
Thank you every much, it makes me face palm when something this simple is the solution to my problem :D
