### ISSUE TITLE
Tournament API

### ISSUE THREAD

**Issue by jvanvugt** [BenFradet/RiotSharp#152]
The Riot Tournament API launched 5 days ago: https://developer.riotgames.com/docs/tournaments-api. Are you planning on implementing it? Otherwise I might look into it.

**Comment by BenFradet** [comment]
I'm indeed planning on implementing it but I have no idea when I'll have the time.

So, if you want to give it a shot, you're more than welcome!

**Comment by BenFradet** [comment]
So, are you working on it, or should I?

**Comment by jvanvugt** [comment]
I was planning on starting sometime next week.

**Comment by BenFradet** [comment]
Well then I'll be awaiting your PR!

**Comment by StevenReitsma** [comment]
Hey @BenFradet, I'm working with @jvanvugt on this issue.

I was looking at the interfaces required, and suggest the following, please let us know whether you think this fits into the existing interface structure.

* `RiotApi` will include a `CreateProvider` method that calls `/tournament/public/v1/provider` and returns a serializable `TournamentProvider` class.
* The `TournamentProvider` will include a `CreateTournament` method that calls `/tournament/public/v1/tournament` and returns a serializable `Tournament` class.
* The `Tournament` will include a `CreateCode` method that calls `/tournament/public/v1/code` and returns a serializable `TournamentCode` class.
* The `TournamentCode` class can be modified and an `Update` method can be called to push the changes to the API server. Alternatively, the `Update` method's arguments can incorporate the changed fields directly. What is preferred?
* `RiotApi` will include a `GetTournamentCodeDetails` that will call the `/tournament/public/v1/code/{tournamentCode}` endpoint and returns a `TournamentCode` object. This could also be added to the constructor of `TournamentCode`, but it seems constructors in RiotSharp are not used in this way, right?
* `RiotApi` will include a `GetTournamentLobbyEvents` that will call the `/tournament/public/v1/lobby/events/by-code/{tournamentCode}` and returns a `TournamentLobbyEvents` object. We will also add a method to `TournamentCode` that will do the same for the current object.
* `RiotApi` will include a method `GetTournamentMatchId` that returns a match-id for a tournament code. This will also be a method of the `TournamentCode` class.
* `RiotApi` will include a method `GetTournamentMatch` that returns a `MatchDetail` object (this class already exists, the DTO for this endpoint and the regular `match` endpoint are equal). The endpoint URL is different, so I think a separate method is better than overloading the `GetMatch` method.
* Maybe combine the `GetTournamentMatchId` and `GetTournamentMatch` into a single method `TournamentCode.GetMatchDetails`?
* + async versions of the above

I'd like to hear your opinion on this. I think the above approaches the current interface structure rather well, but if you think otherwise, feel free to give us suggestions to improve it.

**Comment by BenFradet** [comment]
> Hey @BenFradet, I'm working with @jvanvugt on this issue.
> 
> I was looking at the interfaces required, and suggest the following, please let us know whether you think this fits into the existing interface structure.
> 
> RiotApi will include a CreateProvider method that calls /tournament/public/v1/provider and returns a serializable TournamentProvider class.
> The TournamentProvider will include a CreateTournament method that calls /tournament/public/v1/tournament and returns a serializable Tournament class.
> The Tournament will include a CreateCode method that calls /tournament/public/v1/code and returns a serializable TournamentCode class.

This sounds sensible to me. However, I think this should be into its own API like `TournamentRiotApi`.

> The TournamentCode class can be modified and an Update method can be called to push the changes to the API server. Alternatively, the Update method's arguments can incorporate the changed fields directly. What is preferred?

This is uncharted territory for RiotSharp since before everything was stateless.
However, I think an update method taking the updated fields would be better (changing the state of the object internally). Also, I think, a method callable directly from `TournamentRiotApi` should be supported.

> RiotApi will include a GetTournamentCodeDetails that will call the /tournament/public/v1/code/{tournamentCode} endpoint and returns a TournamentCode object. This could also be added to the constructor of TournamentCode, but it seems constructors in RiotSharp are not used in this way, right?

Adding `GetTournamentCodeDetails` to `TournamentRiotApi` sounds good to me and since there would be an `Update` method in `TournamentCode` why not also a `Get` or `Fetch` method?

> RiotApi will include a GetTournamentLobbyEvents that will call the /tournament/public/v1/lobby/events/by-code/{tournamentCode} and returns a TournamentLobbyEvents object. We will also add a method to TournamentCode that will do the same for the current object.
> RiotApi will include a method GetTournamentMatchId that returns a match-id for a tournament code. This will also be a method of the TournamentCode class.

LGTM, except s/`RiotApi`/`TournamentRiotApi`/g

> RiotApi will include a method GetTournamentMatch that returns a MatchDetail object (this class already exists, the DTO for this endpoint and the regular match endpoint are equal). The endpoint URL is different, so I think a separate method is better than overloading the GetMatch method.
> Maybe combine the GetTournamentMatchId and GetTournamentMatch into a single method TournamentCode.GetMatchDetails?

LGTM

> + async versions of the above
> I'd like to hear your opinion on this. I think the above approaches the current interface structure rather well, but if you think otherwise, feel free to give us suggestions to improve it.
> 
> EDIT: we will also need to add a TournamentRequester that mirrors Requester but for the Tournament API, since it also requires a separate API key. We're gonna have to look into whether it's easier to create a separate TournamentRequester or whether some kind of inheritance is better. Although the latter will be harder since the Requester is a singleton right now.

I think you will have to rework the class hierarchy for `Requester` entirely maybe creating an `IRequester` interface having two children: `UnlimitedRequester` and `RateLimitedRequester` which you would extend as needed.

**Comment by StevenReitsma** [comment]
Thanks for your insights, we'll start working on this tomorrow.

**Comment by BenFradet** [comment]
No problem, thank you guys for contributing!
