### ISSUE TITLE
Move to Microsoft.Net.Http

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#181]
Change the [Requester](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Requester.cs) so it uses [Microsoft HTTP Client Libraries](https://www.nuget.org/packages/Microsoft.Net.Http/) (documentation can be found [here](https://blogs.msdn.microsoft.com/bclteam/2013/02/18/portable-httpclient-for-net-framework-and-windows-phone/)).

**Comment by RejectKid** [comment]
I believe I could do this.  I cloned the repo and all the tests are failing.  Is there something I'm missing?

**Comment by StevenReitsma** [comment]
Did you add your API key to the config?

**Comment by RejectKid** [comment]
ah didnt notice that in the config.  thanks

**Comment by BenFradet** [comment]
Some tests are still currently failing because of the 2016 season, you can track the progress in #189

**Comment by RejectKid** [comment]
So I've converted the base class [Requester](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/Requester.cs) converted over.  The tests that were working are still working.  Currently Ive left the old code there as well because the methods using POST and PUT are failing due to the tournament tests failing mentioned above.  Have y'all figured that out yet? Or possibly how to obtain the tournament Key I need as they appear to be different

**Comment by BenFradet** [comment]
@RejectKid feel free to open the PR and I'll try the changes locally.
