### ISSUE TITLE
Remove ChampionMastery's highestGrade

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#228]
As discussed in [Riot's June 8th update](https://developer.riotgames.com/discussion/announcements/show/qTAtcMAa) `highestGrade` has been removed from the ChampionMastery API.

As a result we should reflect that in RiotSharp,

**Comment by shrayasr** [comment]
Would it be OK if I took this up? I can make the required changes and shoot out a PR your way.

Although how do we make sure that older programs that depend on the existence of `highestGrade` don't break? (Keeping it backward compatible) Should we deprecate it so that people have time to make the change?

**Comment by BenFradet** [comment]
You definitely can pick this up!

We tend to break things fast for small things like this one (like Riot does actually). The reasoning is that people's code should break if they depend on something that doesn't exist.

Otherwise, when there are new versions of existing APIs and, as a result, deprecation of older ones, we follow Riot's guidelines (3-months deprecation and then removal usually).

**Comment by shrayasr** [comment]
Makes sense, allright :) I'll get on it and shoot out a PR soon.

**Comment by BenFradet** [comment]
Great, thanks!
