### ISSUE TITLE
Move the static API to V3

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/RiotSharp#352]
API ref: https://developer.riotgames.com/api-methods/#static-data-v3
Code ref: https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/StaticRiotApi.cs

**Comment by toothlessG22** [comment]
Hello, this is my first attempt at contribution on Github and I have a few questions. For this issue specifically do I just need to replace the old endpoints with the new endpoints? Also, when I try to build the tests, they won't build because some of the parameters are not passed in the tests. (Specifically the tournament test.) Is this a known problem? Thanks.

**Comment by JanOuborny** [comment]
Have you set your API key in the App.conig inside the test project?

**Comment by BenFradet** [comment]
The tests won't build or the tests won't pass?

Also since this is so big of a change I think we'll remove the old endpoints entirely.

**Comment by toothlessG22** [comment]
I have set my API key in the App.config file. The tests will not build because the test code is not passing in the right amount of arguments to the CreateTournament functions. It seems to not be passing in the metadata parameter.

Here is the line where one of the errors occurs:
[TournamentRiotApiTest.cs#L245](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharpTest/TournamentRiotApiTest.cs#L245)

Here is the function that is called from the above line:
[TournamentRiotApi.cs#L119](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/TournamentRiotApi.cs#L119)

Thanks for the help.

**Comment by BenFradet** [comment]
Great catch, those were introduced by #364 , I should have reviewed it more carefully.

Feel free to open an issue and a PR just adding empty strings as metadata to the different calls :+1: .

**Comment by JanOuborny** [comment]
Yep, that's my fault. Forgot to remove the changes. These belonged to the changes regarding the movement to v3. But this should be fixed in my latest PR.
