### ISSUE TITLE
Parameter validation in (Tournament)Api

### ISSUE THREAD

**Issue by JanOuborny** [BenFradet/RiotSharp#362]
I'm not sure about this, but should we provide a parameter validation in any of the APIs to reduce the amount of invalid API calls or should we let Riot's API endpoint handle this. As far as I know we should validate our requests before sending them.

Some examples of missing validation:
- `GetSummonerNames` (Count of `summonerIds `is officially limited to 40. Here it would be useful to determine the real maximal amount of `summonerIds`)
- `GetLeagues `(Count of `teamIds `is officially limited to 10. Also determine real limit.)
- `CreateTournamentCodes `(`count `is limited to 1000, `teamSize `limited to 1-5)

**Comment by BenFradet** [comment]
In the main API, the limits are taken care of by batching according to the advertised limit (e.g. [GetSummoners](https://github.com/BenFradet/RiotSharp/blob/develop/RiotSharp/RiotApi.cs#L138-L161))

That's not true for the tournament API however.

The problem is that Riot doesn't respect the advertised limits, i.e. you can get an invalid call even though you're submitting the right amount of stuff.

Anyway it seems batching is going out in 3.0 according to [this post](https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html). So I personally wouldn't spend time on this as it might get thrown out the window in 3.0.

**Comment by JanOuborny** [comment]
Considering this, I'm going to implement a validation for the tournament api, which should be done quickly.
