### ISSUE TITLE
API FileNotFound Exception

### ISSUE THREAD

**Issue by stefancreed37** [BenFradet/RiotSharp#550]
![image](https://user-images.githubusercontent.com/39136351/40588355-8cd7baae-61dc-11e8-844f-43399baa8727.png)

I've entered username, then clicked Button to receive level, then that happened (In image).

**Comment by BenFradet** [comment]
Are you building from source or using the nuget?

**Comment by stefancreed37** [comment]
From my application

**Comment by Vertana** [comment]
@stefancreed37 I believe he is asking how you installed RiotSharp. Did you build it yourself from source or use nuget? If you used nuget, it would have been a command such as "dotnet add package riotsharp" that you used.


https://www.nuget.org/packages/System.Net.Http/
This link might also help you if you simply don't have it installed.

**Comment by stefancreed37** [comment]
I installed it from my application. Visual Studio > Tools > Github Package Manager > RiotSharp.

I build it manually, added: Button, TextBox, Label.

**Comment by Vertana** [comment]
I've never used that package manager before, but I don't think it has much point here to be honest. The error seems pretty straight forward. It's not finding system.net.http because you don't have that .dll installed.

```bash
 dotnet add package System.Net.Http --version 4.1.1
```

is probably more of what you need. Or since you're on Windows, perhaps you can use the package manager instead:

``` 
Install-Package System.Net.Http -Version 4.1.1
```

If that package manager is automatically building from source, but not running the proper commands to ensure all dependencies are there, I'd recommend either fixing that process or abandoning it and using nuget (outdated) or doing it manually yourself (up to date, but manual work).

**Comment by stefancreed37** [comment]
@Vertana I fixed it with adding System.Net.Http and Newtonsoft to solution. Thank you for help! :+1: 

(You can close this).
